client_data/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from client_data import views
from .views import Client_Data_List, Client_Data_New, Client_Data_Nuevo, Client_Data_Edit, Client_Data_Editar, Client_Data_Delete, Client_Data_Eliminar, Giro_Negocio_List, Giro_Negocio_Nuevo, Giro_Negocio_Editar, Giro_Negocio_Eliminar, Client_Data_To_Excel_1, Client_Data_To_Excel_2, Giro_Negocio_To_Excel_1, Giro_Negocio_To_Excel_2
from .views import clientes

#JJ 
urlpatterns =[
    path('client_data/', Client_Data_List.as_view(), name='client_data_listado'),
    path('client_data/new', Client_Data_New.as_view(), name='client_data_crear'),
    path('client_data/nuevo', Client_Data_Nuevo.as_view(), name='client_data_nuevo'),
    path('cliente/nuevo', clientes, name='cliente_nuevo'),
    path('client_data/edit/<int:pk>', Client_Data_Edit.as_view(), name='client_data_edit'),
    path('client_data/editar/<int:pk>', Client_Data_Editar.as_view(), name='client_data_editar'),
    path('client_data/delete/<int:pk>', Client_Data_Delete.as_view(), name='client_data_delete'),
    path('client_data/eliminar/<int:pk>', Client_Data_Eliminar.as_view(), name='client_data_eliminar'),
    path('client_data/client_data_to_excel_1', Client_Data_To_Excel_1, name='client_data_to_excel_1'),
    path('client_data/client_data_to_excel_2', Client_Data_To_Excel_2, name='client_data_to_excel_2'),
    path('giro_negocio/', Giro_Negocio_List.as_view(), name='giro_negocio_listado'),
    path('giro_negocio/nuevo', Giro_Negocio_Nuevo.as_view(), name='giro_negocio_nuevo'),
    path('giro_negocio/editar/<int:pk>', Giro_Negocio_Editar.as_view(), name='giro_negocio_editar'),
    path('giro_negocio/eliminar/<int:pk>', Giro_Negocio_Eliminar.as_view(), name='giro_negocio_eliminar'),
    path('giro_negocio/giro_negocio_to_excel_1', Giro_Negocio_To_Excel_1, name='giro_negocio_to_excel_1'),
    path('giro_negocio/giro_negocio_to_excel_2', Giro_Negocio_To_Excel_2, name='giro_negocio_to_excel_2'),
]

customers/urls.py
#jazz
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('client_menu.urls')),
    path('', include('client_data.urls')),
    path('', include('client_sales.urls')),
    path('admin/', admin.site.urls),
]

client_data/models.py
from django.db import models


from client_base.models import TablaBase

class Giro_Negocio(TablaBase):
    nombre_giro_negocio=models.CharField(max_length=200,
      unique=True, default='Giro de Negocio'
    )
    codigo_giro_negocio=models.CharField(max_length=10,
      unique=True, default = 'Codigo de Actividad'
    )
    def __str__(self):
      return '{}'.format(self.nombre_giro_negocio)
    class Meta:
      verbose_name_plural = "Giros de Negocio"
      verbose_name = "Giro de Negocio"


class Cliente(TablaBase):
  nombre=models.CharField(
    max_length=100
  )
  nombre_comercial=models.CharField(
    max_length=100,
    null=True, blank=True
  )
  nombre_contacto=models.CharField(
    max_length=100,
    null=True, blank=True
  )
  direccion=models.CharField(
    max_length=250,
    null=True, blank=True
  )
  tipo_documento=models.CharField(
    max_length=30,
    null=True, blank=True
  )
  documento_identidad=models.CharField(
    max_length=20,
    unique=True
  )
  numero_registro_contribuyente=models.CharField(
    max_length=20,
    null=True, blank=True
  )
  giro_negocio=models.ForeignKey( Giro_Negocio, null=True, blank=True,  on_delete=models.CASCADE)
  telefono=models.CharField(
    max_length=10,
    null=True, blank=True
  )
  email=models.CharField(
    max_length=250,
    null=True, blank=True
  )
  categoria_cliente=models.CharField(
    max_length=5,
    null=True, blank=True
  )
  descuento_autorizado=models.FloatField(default=0)

  def __str__(self):
    return '{}'.format(self.nombre)

  def save(self):
    self.nombre=self.nombre.upper()
    super(Cliente, self).save()

  class Meta:
    verbose_name_plural = "Clientes"

client_data/forms.py
from django import forms
from django.http import request
from client_data.models import Cliente, Giro_Negocio
"""
# revisar si se puede usar el widgets para controlar el Textarea de las notas
class Client_Data_Form(forms.Form):
  nombre= forms.CharField(label="Nombre", disabled=True)
"""

TIPO_DOCUMENTO_CHOICES=(("1", "DUI"), ("2", "NIT"), ("3", "PASAPORTE"), ("4", "OTROS"),)

class Client_Data_FormNew(forms.ModelForm):

  class Meta:
    model=Cliente
    fields = ['nombre','tipo_documento','documento_identidad','email',
              'direccion','telefono','numero_registro_contribuyente','giro_negocio' ]
    labels = {'nombre':'Nombre o Razon Social','tipo_documento':'Tipo de Documento Identidad','documento_identidad':'Numero de Documento','email':'Correo Electronico','numero_registro_contribuyente':'Numero de Registro Contribuyente','giro_negocio':'Giro del Negocio'}


  #como se renderiza con bootstrap hay que sobreescribir el metodo init
  def __init__(self, *args, **kwargs):
    super().__init__(*args,**kwargs)
    for field in iter(self.fields):
      self.fields[field].widget.attrs.update({
        'class':'form-control'
      })

class Client_Data_Form(forms.ModelForm):
  # se pueden redifinir los campos de entrada, revisar si valida bien 
  email = forms.EmailField(max_length=254)
  #nombre = forms.TextInput(attrs={"size":5, "title":"Su Nombre"})
  tipo_documento= forms.ChoiceField\
    (label="Tipo de Documento de Identidad", choices=TIPO_DOCUMENTO_CHOICES)
  class Meta:
    model=Cliente
    fields = ['nombre','tipo_documento','documento_identidad','email',
              'direccion','telefono','numero_registro_contribuyente','giro_negocio','nombre_comercial', 'nombre_contacto' ]
    labels = {'nombre':'Nombre o Razon Social','tipo_documento':'Tipo de Documento Identidad','documento_identidad':'Numero de Documento','email':'Correo Electronico','numero_registro_contribuyente':'Numero de Registro Contribuyente','giro_negocio':'Giro del Negocio'}
    #se pueden excluir ciertos campos
    # #exclude = ['modifico', 'modificado', 'creo', 'creado']
    widget={'nombre':forms.TextInput()}
  def __init__(self, *args, **kwargs):
    super().__init__(*args, **kwargs)
    for field in iter(self.fields):
      self.fields[field].widget.attrs.update({
        'class':'form-control'
      })
    
    #self.fields['nombre'].label = 'Usuario'
    #self.fields['nombre'].widget.attrs.update({'class':'primer-grupo'})

  def clean(self):
      try:
          sc = Cliente.objects.get(
              documento_identidad=self.cleaned_data["documento_identidad"].upper()
          )

          if not self.instance.pk:
              print("Documento de Identidad ya existe")
              raise forms.ValidationError("Documento de Identidad Ya Existe")
          elif self.instance.pk!=sc.pk:
              print("Cambio no permitido")
              raise forms.ValidationError("Cambio No Permitido")
      except Cliente.DoesNotExist:
          pass
      return self.cleaned_data

class Giro_Negocio_Form(forms.ModelForm):
  class Meta:
    model=Giro_Negocio
    fields = ['codigo_giro_negocio','nombre_giro_negocio']
  def __init__(self, *args, **kwargs):
    super().__init__(*args, **kwargs)
    for field in iter(self.fields):
      self.fields[field].widget.attrs.update({
        'class':'form-control'
      })

client_data/views.py
from django.shortcuts import render, redirect, get_object_or_404
#from django.contrib.auth.models import User
from client_data.models import Cliente, Giro_Negocio
from .forms import  Client_Data_Form, Client_Data_FormNew, Giro_Negocio_Form
from django.http import HttpResponse, JsonResponse, HttpResponseRedirect
from django.views import generic
from django.urls import reverse_lazy
from django.contrib.messages.views import SuccessMessageMixin
from io import BytesIO
import xlsxwriter
from xlsxwriter.utility import xl_rowcol_to_cell



class MixinFormInvalid():
    def form_invalid(self, form):
        response = super().form_invalid(form)
        #if self.request.is_ajax():
        #if self.request.headers.get('x-requested-with') == 'XMLHttRequest':
        if self.request.accepts("application/json"):
            return JsonResponse(form.errors,status=400)
        else:
            return response

class Client_Data_List(generic.ListView):
    model = Cliente
    template_name = "client_data/client_data_listado.html"
    context_object_name = "clientes"
    #para filtrar los clientes hay que sobreescribir el metodo get_queryset
    def get_queryset(self):
        qs = super().get_queryset()
        return qs

class Client_Data_New(generic.CreateView):
    model=Cliente
    template_name="client_data/client_data_formulario.html"
    context_object_name="clientes"
    form_class=Client_Data_FormNew
    # el CreateView requiere un success_url
    success_url=reverse_lazy("client_data_listar")

class Client_Data_Nuevo(SuccessMessageMixin, MixinFormInvalid, generic.CreateView):
    model=Cliente
    template_name="client_data/client_data_form.html"
    context_object_name="clientes"
    form_class=Client_Data_Form
    success_url=reverse_lazy("client_data_listado")
    success_message="Cliente Agregado Correctamente"
    """
    def form_valid(self, form):
        form.instance.creo= self.request.user
        print(self.request.user.id)
        return super().form_valid(form)
    """
    # revisar en la documentacion oficial de Django [Form handling with class-based views]
    """
    para no repetir codigo hay que crear un Mixin
    def form_invalid(self,form):
        response = super().form_invalid(form)
        if self.request.is_ajax():
            return JsonResponse(form.errors,status=400)
        else:
            return response
    """
# En caso de que el formulario no sea tan estandard
def clientes(request,id=None):
    template_name="client_data/clientes.html"
    giros_negocio = Giro_Negocio.objects.filter(estado=True)
    
    if request.method == "GET":
        cliente = Cliente.objects.filter(pk=id).first()
        if not cliente:
            client = {
                'id':0,
                'nombre':'',
                'nombre_comercial':'',
                'nombre_contacto':'',
                'direcccion':'',
                'tipo_documento':'',
                'documento_identidad':'',
                'numero_registro_contribuyente':'',
                'tipo_documento':'',
                'giro_negocio':'',
                'email':'',
                'categoria_cliente':'',
                'descuento_autorizado':''
            }
        else:
            encabezado = {
                'id':cliente.id,
                'nombre':cliente.nombre,
                'nombre_comercial':cliente.nombre_comercial,
                'nombre_contacto':cliente.nombre_contacto,
                'direcccion':cliente.direccion,
                'tipo_documento':cliente.tipo_documento,
                'documento_identidad':cliente.documento_identidad,
                'numero_registro_contribuyente':cliente.numero_registro_contribuyente,
                'tipo_documento':cliente.tipo_documento,
                'giro_negocio':cliente.giro_negocio,
                'email':cliente.email,
                'categoria_cliente':cliente.categoria_cliente,
                'descuento_autorizado':cliente.descuento_autorizado
            }

        contexto = {"cliente":client,"giros_negocio":giros_negocio}
        return render(request,template_name,contexto)
"""
    if request.method == "POST":
        giro = request.POST.get("cliente_giro_negocio")
        giro_negocio=Giro_Negocio.objects.get(pk=giro)

        if not id:
            cliente = Cliente(
                cliente = cli,
                fecha = fecha
            )
            if enc:
                enc.save()
                id = enc.id
        else:
            enc = FacturaEnca.objects.filter(pk=id).first()
            if enc:
                enc.cliente = cli
                enc.save()

        if not id:
            messages.error(request,'No se puede Continuar No se Detecta No. de Factura')
            return redirect("ventas:factura_list")
        
        codigo = request.POST.get("codigo")
        cantidad = request.POST.get("cantidad")
        precio = request.POST.get("precio")
        s_total = request.POST.get("sub_total_detalle")
        descuento = request.POST.get("descuento_detalle")
        total = request.POST.get("total_detalle")

        prod = Producto.objects.get(codigo=codigo)
        det = FacturaDeta(
            factura = enc,
            producto = prod,
            cantidad = cantidad,
            precio = precio,
            sub_total = s_total,
            descuento = descuento,
            total = total
        )
        
        if det:
            det.save()
        
        return redirect("ventas:factura_edit",id=id)

    return render(request,template_name,contexto)
"""    



class Client_Data_Edit(generic.UpdateView):
    model=Cliente
    template_name="client_data/client_data_formulario.html"
    context_object_name="clientes"
    form_class=Client_Data_FormNew
    # el CreateView requiere un success_url
    success_url=reverse_lazy("client_data_listar")
    success_message="Cliente Actualizado Exitosamente"

class Client_Data_Editar(SuccessMessageMixin, MixinFormInvalid, generic.UpdateView):
    model=Cliente
    template_name="client_data/client_data_form.html"
    context_object_name="clientes"
    form_class=Client_Data_Form
    # el CreateView requiere un success_url
    success_url=reverse_lazy("client_data_listado")
    success_message="Cliente Actualizado Exitosamente"

class Client_Data_Delete(generic.DeleteView):
    model=Cliente
    template_name="client_data/client_data_delete.html"
    context_object_name="clientes"
    success_url=reverse_lazy("client_data_listar")

class Client_Data_Eliminar(generic.DeleteView):
    model=Cliente
    template_name="client_data/client_data_eliminar.html"
    context_object_name="clientes"
    success_url=reverse_lazy("client_data_listado")

class Giro_Negocio_List(generic.ListView):
    model = Giro_Negocio
    template_name = "client_data/giro_negocio_listado.html"
    context_object_name = "giros_negocio"
    #para filtrar las ventas_a_cliente hay que sobreescribir el metodo get_queryset
    def get_queryset(self):
        qs = super().get_queryset()
        return qs


class Giro_Negocio_Nuevo(SuccessMessageMixin, MixinFormInvalid, generic.CreateView):
    model=Giro_Negocio
    template_name="client_data/giro_negocio_form.html"
    context_object_name="giros_negocio"
    form_class=Giro_Negocio_Form
    success_url=reverse_lazy("giro_negocio_listado")
    success_message="Giro Negocio Agregado Correctamente"

class Giro_Negocio_Editar(SuccessMessageMixin, MixinFormInvalid, generic.UpdateView):
    model=Giro_Negocio
    template_name="client_data/giro_negocio_form.html"
    context_object_name="giros_negocio"
    form_class=Giro_Negocio_Form
    success_url=reverse_lazy("giro_negocio_listado")
    success_message="Giro Negocio Actualizado Exitosamente"

class Giro_Negocio_Eliminar(generic.DeleteView):
    model=Giro_Negocio
    template_name="client_data/giro_negocio_eliminar.html"
    context_object_name="giros_negocio"
    success_url=reverse_lazy("giro_negocio_listado")

class Client_Data_To_Pdf(generic.DeleteView):
    model=Cliente
    template_name="client_data/client_data_to_pdf.html"
    context_object_name="clientes"
    success_url=reverse_lazy("client_data_listado")

def Client_Data_To_Excel_1(request):
    context = {
        'archivo': 'DatosCleiente',
    }

    return render(request, 'client_data/client_data_to_excel_1.html', {'context': context})


def Client_Data_To_Excel_2(request):

    queryset_list = Cliente.objects.values('nombre','tipo_documento','documento_identidad','email','direccion','telefono','numero_registro_contribuyente','giro_negocio','nombre_comercial','nombre_contacto')
    #contenido del campo archivo
    if 'archivo' in request.GET:
        archivo = request.GET['archivo']

    # Crear un objeto (object) para crear archivos en memoria
    temp_file = BytesIO()

    # Empezar un libro (workbook)
    workbook = xlsxwriter.Workbook(temp_file)
    worksheet = workbook.add_worksheet()
    
    # Prepararar los datos a escribirse
    data = []
    for cliente in queryset_list:
        nombre=cliente['nombre']
        tipo_documento=cliente['tipo_documento']
        documento_identidad=cliente['documento_identidad']
        email=cliente['email']
        direccion=cliente['direccion']
        telefono=cliente['telefono']
        numero_registro_contribuyente=cliente['numero_registro_contribuyente']
        giro_negocio=cliente['giro_negocio']
        nombre_comercial=cliente['nombre_comercial']
        nombre_contacto=cliente['nombre_contacto']
        #nombre de giro
        if giro_negocio:
            giro = Giro_Negocio.objects.filter(id=giro_negocio).first()
            nombregiro=giro.nombre_giro_negocio
        else:
            nombregiro='Sin Giro de Negocio'

        #nombre de Tipo de documento
        nombretipo='Sin Tipo de Documento'

        match tipo_documento:
            case '1':
                nombretipo = "DUI"
            case '2':
                nombretipo = "NIT"
            case '3':

client_data/templates/client_data/client_data_delete.html
{% extends 'navegacion.html' %}
{% block title %} | client_data_eliminar {% endblock %}
{% block titulo %}
Formulario para eliminar Clientes
{% endblock titulo %}
{% block content %}
<form method="POST" id="frmclient_data_eliminar" class="form-inline">
  {% csrf_token %}
  <div class="card my-5 mx-5">
    <div class="card border-danger shadow h-100 py-2">
      <div class="card-body">
        <div class="row no-gutters align-items-center">
          <div class="col mr-2">
            <div class="text-xs font-weight-bold text-warning text-uppercase mb-1">Esta seguro de eliminar: {{clientes.nombre}}?</div>
            <button type="submit" class="btn btn-danger"><i class="far fa-question-circle"></i>Eliminar</button>
            <a href="{% url 'client_data_listar' %}" class="btn btn-success"><span class="fa fa-undo"></span>Cancelar</a>
          </div>
          <div class="col-auto">
            <i class="far fa-question-circle fa-2x text-gray-300"></i>
          </div>
        </div>
      </div>
    </div>
  </div>
</form>
{% endblock %}
{% block js_page %}
{% endblock js_page %} 

client_data/templates/client_data/client_data_eliminar.html
{% extends 'navegacion.html' %}
{% block title %} | client_data_eliminar {% endblock %}
{% block titulo %}
Formulario para eliminar Clientes
{% endblock titulo %}
{% block content %}
<form method="POST" id="frmclient_data_eliminar" class="form-inline">
  {% csrf_token %}
  <div class="card my-5 mx-5">
    <div class="card border-danger shadow h-100 py-2">
      <div class="card-body">
        <div class="row no-gutters align-items-center">
          <div class="col mr-2">
            <div class="text-xs font-weight-bold text-warning text-uppercase mb-1">Esta seguro de eliminar: {{clientes.nombre}}?</div>
            <button type="submit" class="btn btn-danger"><i class="far fa-question-circle"></i>Eliminar</button>
            <a href="{% url 'client_data_listado' %}" class="btn btn-success"><span class="fa fa-undo"></span>Cancelar</a>
          </div>
          <div class="col-auto">
            <i class="far fa-question-circle fa-2x text-gray-300"></i>
          </div>
        </div>
      </div>
    </div>
  </div>
</form>
{% endblock %}
{% block js_page %}
{% endblock js_page %} 

client_data/templates/client_data/client_data_form.html
<div class="modal-dialog modal-xl">
  <div class="modal-content">
    {% if clientes %}
    <form method="POST" role="form" class="form-inline" action="{% url 'client_data_editar' clientes.pk %}">
      {% else %}
      <form method="POST" role="form" class="form-inline" action="{% url 'client_data_nuevo' %}">
        {% endif %}
        <div class="col-xl-12 col-md-12 mb-12">
          {% if clientes %}
          <div class="card border-left-warning shadow h-100 py-2">
            {% else %}
            <div class="card border-left-success shadow h-100 py-2">
              {% endif %}

              <div class="card-body">
                <div class="row no-gutters align-items-center">
                  <div class="col mr-2">
                    <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">{% if clientes %} Editar
                      {% else %} Nuevo {% endif %} Cliente
                    </div>
                    <div class="dropdown-divider"></div>
                    {% csrf_token %}
                    <div class="alert alert-primary" role="alert">
                      <div class="row">
                        <div class="col-2 text-lg font-weight-bold text-success">Nombre o Razon Social</div>
                        <div class="col-4">
                          <div class="input-group">
                            {{ form.nombre }}
                          </div>
                        </div>
                        <div class="col-2 text-sm font-weight-bold text-success">Tipo de Documento de Identidad</div>
                        <div class="col-4">
                          <div class="input-group">
                            {{ form.tipo_documento }}
                          </div>
                        </div>
                      </div>
                      <br>
                      <div class="row">
                        <div class="col-2 font-weight-bold text-success">Numero de Documento</div>
                        <div class="col-4">
                          <div class="input-group">
                            {{ form.documento_identidad }}
                          </div>
                        </div>
                        <div class="col-2 font-weight-bold text-success">Correo Electronico</div>
                        <div class="col-4">
                          <div class="input-group">
                            {{ form.email }}
                          </div>
                        </div>
                      </div>
                    </div>
                    <div class="alert alert-success" role="alert">
                      <div class="row">
                        <div class="col-2 text-lg font-weight-bold text-success">Direccion</div>
                        <div class="col-4">
                          <div class="input-group">
                            {{ form.direccion }}
                          </div>
                        </div>
                        <div class="col-2 text-sm font-weight-bold text-success">Numero de Telefono</div>
                        <div class="col-4">
                          <div class="input-group">
                            {{ form.telefono }}
                          </div>
                        </div>
                      </div>
                    </div>
                    <div class="alert alert-danger" role="alert">
                      <div class="row">
                        <div class="col-2 text-lg font-weight-bold text-success">Numero de Registro del Contribuyente</div>
                        <div class="col-4">
                          <div class="input-group">
                            {{ form.numero_registro_contribuyente }}
                          </div>
                        </div>
                        <div class="col-2 text-sm font-weight-bold text-success">Giro del Negocio</div>
                        <div class="col-4">
                          <div class="input-group">
                            {{ form.giro_negocio }}
                          </div>
                        </div>
                      </div>
                    </div>
                    <div class="alert alert-warning" role="alert">
                      <div class="row">
                        <div class="col-2 text-lg font-weight-bold text-success">Nombre Comercial</div>
                        <div class="col-4">
                          <div class="input-group">
                            {{ form.nombre_comercial }}
                          </div>
                        </div>
                        <div class="col-2 text-sm font-weight-bold text-success">Nombre del Contacto</div>
                        <div class="col-4">
                          <div class="input-group">
                            {{ form.nombre_contacto }}
                          </div>
                        </div>
                      </div>
                    </div>
                    <div class="dropdown-divider"></div>
                    <div class="row">
                      <div class="col">
                        <button type="submit" class="btn btn-danger"><span class="fa fa-save"></span>Guardar</button>
                        <button type="button" class="btn btn-success" onclick="return cerrar_modal()">Cancelar</button>
                      </div>
                    </div>

                  </div>
                </div>
              </div>
            </div>
          </div>
      </form>
  </div>
</div>
<script>
  $(function () {
    $('#id_giro_negocio').select2({
      placeholder: "Seleccione Giro de Negocio",
      allowClear: true,
      dropdownParent: $('#popup'),
      width: '100%'
  });
  // es necesario usar el dropdownParent cuando el select2 esta en una ventada modal
  //$.fn.modal.Constructor.prototype._enforceFocus = function(){}

    var url = $("form").attr("action");
    //en django se necesita el token de seguridad, con f12 abrimos la ventana de desarrollador, luego en network al abrir el formulario de nuevo cliente si damos click en la respuesta podemos ver el preview del formulario y en response el codigo del mismo de alli podemos tomar el nombre del token
    var token = jQuery("[name=csrfmiddlewaretoken]").val();

    $("form").submit(function (e) {
      //prevenir el envio del formulario en caso de error, por ejemplo al agregar un cliente duplicado
      e.preventDefault();
      // alert(url);
      // alert(token);
      var formData = $("form").serializeArray();
      // console.log(formData);
      $.ajax({
          url: url,
          method: "POST",
          headers: {'X-CSRFToken': token},
          data: formData
        })
        .done(function (r, textStatus, xhr) {
          if (xhr.status = 200) {
            location.reload(true);
          } else {
            mensaje(textStatus);
          }
        }).fail(function (error) {
          mensaje(error.responseText);
        });
    });
  });
</script>

client_data/templates/client_data/giro_negocio_form.html
<div class="modal-dialog modal-lg">t_data
  <div class="modal-content">
    {% if giros_negocio %}
    <form method="POST" role="form" class="form-inline" action="{% url 'giro_negocio_editar' giros_negocio.pk %}">
      {% else %}
      <form method="POST" role="form" class="form-inline" action="{% url 'giro_negocio_nuevo' %}">
        {% endif %}
        <div class="col-xl-12 col-md-12 mb-12">
          {% if giros_negocio %}
          <div class="card border-left-warning shadow h-100 py-2">
            {% else %}
            <div class="card border-left-success shadow h-100 py-2">
              {% endif %}
              <div class="card-body">
                <div class="row no-gutters align-items-center">
                  <div class="col mr-2">
                    <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">{% if giros_negocio %} Editar
                      {% else %} Nuevo {% endif %} Giro de Negocio</div>
                    <div class="dropdown-divider"></div>
                    {% csrf_token %}
                    <div class="row">
                      {{ form.as_p }}
                    </div>
                    <div class="dropdown-divider"></div>
                    <div class="row">
                      <div class="col">
                        <button type="submit" class="btn btn-danger"><span class="fa fa-save"></span>Guardar</button>
                        <button type="button" class="btn btn-success" onclick="return cerrar_modal()">Cancelar</button>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
      </form>
  </div>
</div>
<script>
    /*Validar Envío de formulario */
    $("form").submit(function (e) {

      /* Inicio Validar Nombre Giro de Negocio */
      var nombre_giro_negocio = $("#id_nombre_giro_negocio").val();
      if (nombre_giro_negocio.trim() == "") {
        e.preventDefault()
        $.alert({
          type: 'red',
          title: '',
          content: 'Debe Especificar el Nombre del Giro de Negocio'
        });
        return false;
      }
      /* Final Validar Nombre Giro de Negocio */
      /* Inicio Validar Codigo de Giro de Negocio */
      var codigo_giro_negocio = $("#id_codigo_giro_negocio").val();
      if (codigo_giro_negocio.trim() == "") {
        e.preventDefault()
        $.alert({
          type: 'red',
          title: '',
          content: 'Debe Especificar el Codigo del Giro de Negocio'
        });
        return false;
      }
      /* Fin Validar Codigo de Giro de Negocio */
    });
    /*Fin Validar Envío de Formulario */

</script>