client_sales/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from client_sales import views
from .views import Client_Sales_List, Client_Sales_Nuevo, Client_Sales_Editar, Client_Sales_Eliminar
from .views import Sucursal_List, Sucursal_Nuevo, Sucursal_Editar, Sucursal_Eliminar

#JJ 
urlpatterns =[
    path('client_sales/', Client_Sales_List.as_view(), name='client_sales_listado'),
    path('client_sales/nuevo', Client_Sales_Nuevo.as_view(), name='client_sales_nuevo'),
    path('client_sales/editar/<int:pk>', Client_Sales_Editar.as_view(), name='client_sales_editar'),
    path('client_sales/eliminar/<int:pk>', Client_Sales_Eliminar.as_view(), name='client_sales_eliminar'),
    path('sucursal/', Sucursal_List.as_view(), name='sucursal_listado'),
    path('sucursal/nuevo', Sucursal_Nuevo.as_view(), name='sucursal_nuevo'),
    path('sucursal/editar/<int:pk>', Sucursal_Editar.as_view(), name='sucursal_editar'),
    path('sucursal/eliminar/<int:pk>', Sucursal_Eliminar.as_view(), name='sucursal_eliminar'),
]

customers/urls.py
#jazz
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('client_menu.urls')),
    path('', include('client_data.urls')),
    path('', include('client_sales.urls')),
    path('admin/', admin.site.urls),
]

client_sales/models.py
from django.db import models
from django.utils import timezone


from client_base.models import TablaBase
from client_data.models import Cliente

#para que devuelva solo la fecha sin la hora
def hoy():
    return timezone.now().date() 


class Sucursal(TablaBase):
    nombre_sucursal=models.CharField(max_length=100,
      unique=True, default='Nombre'
    )
    codigo_sucursal=models.CharField(max_length=10,
      unique=True, default = 'Codigo'
    )
    def __str__(self):
      return '{}'.format(self.nombre_sucursal)
    class Meta:
      verbose_name_plural = "Sucursales"
      verbose_name = "Sucursal"

class Ventas_a_Cliente(TablaBase):
    sucursal_venta=models.ForeignKey(Sucursal, on_delete=models.CASCADE)
    cliente_venta=models.ForeignKey(Cliente, on_delete=models.CASCADE)
    fecha_venta=models.DateField(default=hoy)
    documento_venta=models.CharField(max_length=100, blank=True)
    total_venta=models.FloatField(default=0)
    descuento_venta=models.FloatField(default=0)
    def __str__(self):
      return '{}:{}'.format(self.sucursal_venta.nombre,self.documento_venta)
    class Meta:
      verbose_name_plural = "Ventas a Clientes"
      verbose_name = "Venta a Cliente"
      unique_together = ('sucursal_venta','documento_venta')

client_sales/forms.py
from django import forms
from django.http import request
from client_data.models import Cliente
from client_sales.models import Ventas_a_Cliente, Sucursal

class Client_Sales_Form(forms.ModelForm):
  fecha_venta = forms.DateInput(format='%Y-%m-%d')
  #fecha_venta = forms.DateField(
    #widget=forms.DateInput(format='%Y-%m-%d'),input_formats=['%Y-%m-%d']
  #)
  class Meta:
    model=Ventas_a_Cliente
    fields = ['sucursal_venta','cliente_venta','fecha_venta','documento_venta','total_venta',
              'descuento_venta' ]
  def __init__(self, *args, **kwargs):
    super().__init__(*args, **kwargs)
    for field in iter(self.fields):
      self.fields[field].widget.attrs.update({
        'class':'form-control'
      })
      self.fields['fecha_venta'].widget.attrs['readonly'] = True

class Sucursal_Form(forms.ModelForm):
  class Meta:
    model=Sucursal
    fields = ['nombre_sucursal','codigo_sucursal']
  def __init__(self, *args, **kwargs):
    super().__init__(*args, **kwargs)
    for field in iter(self.fields):
      self.fields[field].widget.attrs.update({
        'class':'form-control'
      })

client_sales/views.py
from django.shortcuts import render, redirect, get_object_or_404
#from django.contrib.auth.models import User
from client_data.models import Cliente
from client_sales.models import Ventas_a_Cliente, Sucursal
from .forms import  Client_Sales_Form, Sucursal_Form
from django.http import HttpResponse, JsonResponse
from django.views import generic
from django.urls import reverse_lazy
from django.contrib.messages.views import SuccessMessageMixin

#este mixin se puede incluir en la aplicacion base
class MixinFormInvalid():
    def form_invalid(self, form):
        response = super().form_invalid(form)
        #if self.request.is_ajax(): #deprecated
        #if self.request.headers.get('x-requested-with') == 'XMLHttRequest':
        if self.request.accepts("application/json"):
            return JsonResponse(form.errors,status=400)
        else:
            return response

class Client_Sales_List(generic.ListView):
    model = Ventas_a_Cliente
    template_name = "client_sales/client_sales_listado.html"
    context_object_name = "ventas_a_clientes"
    #para filtrar las ventas_a_cliente hay que sobreescribir el metodo get_queryset
    def get_queryset(self):
        qs = super().get_queryset()
        return qs


class Client_Sales_Nuevo(SuccessMessageMixin, MixinFormInvalid, generic.CreateView):
    model=Ventas_a_Cliente
    template_name="client_sales/client_sales_form.html"
    context_object_name="ventas_a_clientes"
    form_class=Client_Sales_Form
    success_url=reverse_lazy("client_sales_listado")
    success_message="Cliente Agregado Correctamente"
    """
    def form_valid(self, form):
        form.instance.creo= self.request.user
        print(self.request.user.id)
        return super().form_valid(form)
    """

class Client_Sales_Editar(SuccessMessageMixin, MixinFormInvalid, generic.UpdateView):
    model=Ventas_a_Cliente
    template_name="client_sales/client_sales_form.html"
    context_object_name="ventas_a_clientes"
    form_class=Client_Sales_Form
    # el CreateView requiere un success_url
    success_url=reverse_lazy("client_sales_listado")
    success_message="Cliente Actualizado Exitosamente"

class Client_Sales_Eliminar(generic.DeleteView):
    model=Ventas_a_Cliente
    template_name="client_sales/client_sales_eliminar.html"
    context_object_name="ventas_a_clientes"
    success_url=reverse_lazy("client_sales_listado")
#sucursales

class Sucursal_List(generic.ListView):
    model = Sucursal
    template_name = "client_sales/sucursal_listado.html"
    context_object_name = "sucursales"
    #para filtrar las ventas_a_cliente hay que sobreescribir el metodo get_queryset
    def get_queryset(self):
        qs = super().get_queryset()
        return qs


class Sucursal_Nuevo(SuccessMessageMixin, MixinFormInvalid, generic.CreateView):
    model=Sucursal
    template_name="client_sales/sucursal_form.html"
    context_object_name="sucursales"
    form_class=Sucursal_Form
    success_url=reverse_lazy("sucursal_listado")
    success_message="Sucursal Agregada Correctamente"

class Sucursal_Editar(SuccessMessageMixin, MixinFormInvalid, generic.UpdateView):
    model=Sucursal
    template_name="client_sales/sucursal_form.html"
    context_object_name="sucursales"
    form_class=Sucursal_Form
    success_url=reverse_lazy("sucursal_listado")
    success_message="Sucursal Actualizada Exitosamente"

class Sucursal_Eliminar(generic.DeleteView):
    model=Sucursal
    template_name="client_sales/sucursal_eliminar.html"
    context_object_name="sucursales"
    success_url=reverse_lazy("sucursal_listado")

client_sales/templates/client_sales/client_sales_eliminar.html
{% extends 'navegacion.html' %}
{% block title %} | client_sales_eliminar {% endblock %}
{% block titulo %}
Formulario para Eliminar Ventas a Clientes
{% endblock titulo %}
{% block content %}
<form method="POST" id="frmclient_sales_eliminar" class="form-inline">
  {% csrf_token %}
  <div class="card my-5 mx-5">
    <div class="card border-danger shadow h-100 py-2">
      <div class="card-body">
        <div class="row no-gutters align-items-center">
          <div class="col mr-2">
            <div class="text-xs font-weight-bold text-warning text-uppercase mb-1">Esta seguro de eliminar Documento: {{ventas_a_clientes.documento_venta}} de Sucursal: {{ventas_a_clientes.sucursal_venta}} ?</div>
            <button type="submit" class="btn btn-danger"><i class="far fa-question-circle"></i>Eliminar</button>
            <a href="{% url 'client_sales_listado' %}" class="btn btn-success"><span class="fa fa-undo"></span>Cancelar</a>
          </div>
          <div class="col-auto">
            <i class="far fa-question-circle fa-2x text-gray-300"></i>
          </div>
        </div>
      </div>
    </div>
  </div>
</form>
{% endblock %}
{% block js_page %}
{% endblock js_page %} 

client_sales/templates/client_sales/client_sales_form.html
<div class="modal-dialog modal-lg">
  <div class="modal-content">
    {% if ventas_a_clientes %}
    <form method="POST" role="form" class="form-inline" action="{% url 'client_sales_editar' ventas_a_clientes.pk %}">
      {% else %}
      <form method="POST" role="form" class="form-inline" action="{% url 'client_sales_nuevo' %}">
        {% endif %}
        <div class="col-xl-12 col-md-12 mb-12">
          {% if ventas_a_clientes %}
          <div class="card border-left-warning shadow h-100 py-2">
            {% else %}
            <div class="card border-left-success shadow h-100 py-2">
              {% endif %}
              <div class="card-body">
                <div class="row no-gutters align-items-center">
                  <div class="col mr-2">
                    <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">{% if ventas_a_clientes %} Editar
                      {% else %} Nueva {% endif %} Venta a Cliente</div>
                    <div class="dropdown-divider"></div>
                    {% csrf_token %}
                    <div class="row">
                      {{ form.as_p }}
                    </div>
                    <div class="dropdown-divider"></div>
                    <div class="row">
                      <div class="col">
                        <button type="submit" class="btn btn-danger"><span class="fa fa-save"></span>Guardar</button>
                        <button type="button" class="btn btn-success" onclick="return cerrar_modal()">Cancelar</button>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
      </form>
  </div>
</div>
<script>
  $(function () {
      /* control de fecha */
      jQuery.datetimepicker.setLocale('es');
      $('#id_fecha_venta').datetimepicker({
        i18n:{
          es:{
            months:[
              'Enero','Febrero','Marzo','Abril','Mayo','Junio','Julio','Agosto',
              'Septiembre','Octubre','Noviembre','Diciembre',
            ],
            dayOfWeek:[
              'Dom','Lum','Mar','Mie','Jue','Vie','Sab',
            ]
          }
        },
        format: "Y-m-d",
        timepicker: false
      });
      /* control de fecha */
    });
    /*Validar Envío de formulario */
    $("form").submit(function (e) {

      /* Inicio Validar Sucursal */
      var sucursal_venta = $("#id_sucursal_venta").val();
      if (sucursal_venta.trim() == "") {
        e.preventDefault()
        $.alert({
          type: 'red',
          title: '',
          content: 'Debe Especificar la Sucursal'
        });
        return false;
      }
      /* Final Validar Sucursal */
      /* Inicio Validar Cliente */
      var cliente_venta = $("#id_cliente_venta").val();
      if (cliente_venta.trim() == "") {
        e.preventDefault()
        $.alert({
          type: 'red',
          title: '',
          content: 'Debe Especificar el Cliente'
        });
        return false;
      }
      /* Fin Validar Cliente */
      /* Inicio Validar el documento */
      var documento_venta = $("#id_documento_venta").val();
      if (documento_venta == "") {
        e.preventDefault()
        $.alert({
          type: 'red',
          title: '',
          content: 'Debe especificar el documento de Venta'
        });
        return false;
      }
      /* Fin Validar el documento */
      /* Inicio Validar el total de la venta */
      var total_venta = $("#id_total_venta").val();
      if (total_venta <= 0) {
        e.preventDefault()
        $.alert({
          type: 'red',
          title: '',
          content: 'Debe especificar el Total de la Venta'
        });
        return false;
      }
      /* Fin Validar el total de la venta */
    });
    /*Fin Validar Envío de Formulario */

</script>

client_sales/templates/client_sales/client_sales_listado.html
{% extends 'navegacion.html' %}
{% block title %} | client_sales_listado {% endblock title %}

{% block titulo %}
Listado de Ventas a Clientes
{% endblock titulo %}
{% block content %}
<div class="card shadow mb-4">
  <!-- Card Header - Dropdown -->
  <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between" >
    <h6 class="m-0 font-weight-bold text-primary">Listado de Ventas a Clientes</h6>
    <a href="#" class="btn btn-success btn-circle" role="button" onclick="return abrir_modal('{% url 'client_sales_nuevo' %}')" ><i
      class="far fa-edit"></i>Nueva Venta a Cliente</a>
    </div>
  <!-- Card Body -->
  <div class="card-body">
    {% if not ventas_a_clientes %}
    <div class="alert alert-info">No hay Ventas a Clientes</div>
    {% else %}
    <table class="table table-striped table-hover dt-responsive nowrap" style="width:100%">
      <thead>
        <th>Sucursal</th>
        <th>Cliente</th>
        <th>Fecha</th>
        <th>Documento</th>
        <th>Total</th>
        <th>Descuento</th>
        <th class="all">Acciones</th>
      </thead>
    <tbody>
      {% for venta in ventas_a_clientes %}
      <tr>
        <td>{{ venta.sucursal_venta }}</td>
        <td>{{ venta.cliente_venta }}</td>
        <td>{{ venta.fecha_venta }}</td>
        <td>{{ venta.documento_venta }}</td>
        <td>{{ venta.total_venta }}</td>
        <td>{{ venta.descuento_venta }}</td>
        <td>
          <button class="btn btn-warning btn-circle" onclick="return abrir_modal('{% url 'client_sales_editar'  venta.id %}')"><i class="far fa-edit"></i></button>
          <a href="{% url 'client_sales_eliminar' venta.id %}" class="btn btn-danger btn-circle" role="button"><i class="far fa-trash-alt"></i></a>
  </td>
      </tr>
      {% endfor %}
    </tbody>
    </table>
    {% endif %}
  </div>
</div>

{% endblock content %}
{% block js_page %}
  <script>
    //call the datatables jQuery plugin
    $(document).ready(function(){
      $('.table').DataTable({
        "pageLength": 8,
        "language":{
          "sProcessing": "Procesando...",
          "sLengthMenu": "Mostrar _MENU_ registros",
          "sZeroRecords": "No existen registros",
          "sEmptyTable": "La tabla esta vacia",
          "sInfo": "Mostrando registros del _START_ al _END_ de un total de _TOTAL_ registros",
          "sInfoEmpty": "Mostrando registros del 0 al 0 de un total de 0 registros",
          "sInfoFiltered": "(filtrado de un total de _MAX_ registros)",
          "sInfoPostFix": "",
          "sSearch": "Buscar:",
          "sUrl": "",
          "sInfoThousands": ",",
          "sLoadingRecords": "Cargando registros...",
          "sPaginate": {
            "sFirst":"<span class='fa fa-angle-double-left'></span>",
            "sLast":"<span class='fa fa-angle-double-right'></span>",
            "sNext":"<span class='fa fa-angle-right'></span>",
            "sPrevious":"<span class='fa fa-angle-left'></span>"
          },
          "oAria":{
            "sSortAscending":": Activar para ordenar la columna de manera ascendente",
            "sSortDescending":": Activar para ordenar la columna de manera descendente"
          }
        }
      });

    });
  </script>
{% endblock js_page %}

client_sales/templates/client_sales/sucursal_eliminar.html
{% extends 'navegacion.html' %}
{% block title %} | sucursal_eliminar {% endblock %}
{% block titulo %}
Formulario para Eliminar Sucursales
{% endblock titulo %}
{% block content %}
<form method="POST" id="frmclient_sales_eliminar" class="form-inline">
  {% csrf_token %}
  <div class="card my-5 mx-5">
    <div class="card border-danger shadow h-100 py-2">
      <div class="card-body">
        <div class="row no-gutters align-items-center">
          <div class="col mr-2">
            <div class="text-xs font-weight-bold text-warning text-uppercase mb-1">Esta seguro de eliminar Sucursal: {{sucursales.codigo_sucursal}} - {{sucursales.nombre_sucursal}} ?</div>
            <button type="submit" class="btn btn-danger"><i class="far fa-question-circle"></i>Eliminar</button>
            <a href="{% url 'sucursal_listado' %}" class="btn btn-success"><span class="fa fa-undo"></span>Cancelar</a>
          </div>
          <div class="col-auto">
            <i class="far fa-question-circle fa-2x text-gray-300"></i>
          </div>
        </div>
      </div>
    </div>
  </div>
</form>
{% endblock %}
{% block js_page %}
{% endblock js_page %} 

client_sales/templates/client_sales/sucursal_form.html
<div class="modal-dialog modal-lg">
  <div class="modal-content">
    {% if sucursales %}
    <form method="POST" role="form" class="form-inline" action="{% url 'sucursal_editar' sucursales.pk %}">
      {% else %}
      <form method="POST" role="form" class="form-inline" action="{% url 'sucursal_nuevo' %}">
        {% endif %}
        <div class="col-xl-12 col-md-12 mb-12">
          {% if sucursales %}
          <div class="card border-left-warning shadow h-100 py-2">
            {% else %}
            <div class="card border-left-success shadow h-100 py-2">
              {% endif %}
              <div class="card-body">
                <div class="row no-gutters align-items-center">
                  <div class="col mr-2">
                    <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">{% if sucursales %} Editar
                      {% else %} Nueva {% endif %} Sucursal</div>
                    <div class="dropdown-divider"></div>
                    {% csrf_token %}
                    <div class="row">
                      {{ form.as_p }}
                    </div>
                    <div class="dropdown-divider"></div>
                    <div class="row">
                      <div class="col">
                        <button type="submit" class="btn btn-danger"><span class="fa fa-save"></span>Guardar</button>
                        <button type="button" class="btn btn-success" onclick="return cerrar_modal()">Cancelar</button>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
      </form>
  </div>
</div>
<script>
    /*Validar Envío de formulario */
    $("form").submit(function (e) {

      /* Inicio Validar Nombre Sucursal */
      var nombre_sucursal = $("#id_nombre_sucursal").val();
      if (nombre_sucursal.trim() == "") {
        e.preventDefault()
        $.alert({
          type: 'red',
          title: '',
          content: 'Debe Especificar el Nombre de la Sucursal'
        });
        return false;
      }
      /* Final Validar Nombre Sucursal */
      /* Inicio Validar Codigo de Sucursal */
      var codigo_sucursal = $("#id_codigo_sucursal").val();
      if (codigo_sucursal.trim() == "") {
        e.preventDefault()
        $.alert({
          type: 'red',
          title: '',
          content: 'Debe Especificar el Codigo de la Sucursal'
        });
        return false;
      }
      /* Fin Validar Codigo de Sucursal */
    });
    /*Fin Validar Envío de Formulario */

</script>

client_sales/templates/client_sales/sucursal_listado.html
{% extends 'navegacion.html' %}
{% block title %} | sucursal_listado {% endblock title %}

{% block titulo %}
Listado de Sucursales
{% endblock titulo %}
{% block content %}
<div class="card shadow mb-4">
  <!-- Card Header - Dropdown -->
  <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between" >
    <h6 class="m-0 font-weight-bold text-primary">Listado de Sucursales</h6>
    <a href="#" class="btn btn-success btn-circle" role="button" onclick="return abrir_modal('{% url 'sucursal_nuevo' %}')" ><i
      class="far fa-edit"></i>Nueva Sucursal</a>
    </div>
  <!-- Card Body -->
  <div class="card-body">
    {% if not sucursales %}
    <div class="alert alert-info">No existen Sucursales</div>
    {% else %}
    <table class="table table-striped table-hover dt-responsive nowrap" style="width:100%">
      <thead>
        <th>Codigo de Sucursal</th>
        <th>Nombre de Sucursal</th>
        <th class="all">Acciones</th>
      </thead>
    <tbody>
      {% for sucursal in sucursales %}
      <tr>
        <td>{{ sucursal.codigo_sucursal }}</td>
        <td>{{ sucursal.nombre_sucursal }}</td>
        <td>
          <button class="btn btn-warning btn-circle" onclick="return abrir_modal('{% url 'sucursal_editar'  sucursal.id %}')"><i class="far fa-edit"></i></button>
          <a href="{% url 'sucursal_eliminar' sucursal.id %}" class="btn btn-danger btn-circle" role="button"><i class="far fa-trash-alt"></i></a>
  </td>
      </tr>
      {% endfor %}
    </tbody>
    </table>
    {% endif %}
  </div>
</div>

{% endblock content %}
{% block js_page %}
  <script>
    //call the datatables jQuery plugin
    $(document).ready(function(){
      $('.table').DataTable({
        "pageLength": 8,
        "language":{
          "sProcessing": "Procesando...",
          "sLengthMenu": "Mostrar _MENU_ registros",
          "sZeroRecords": "No existen registros",
          "sEmptyTable": "La tabla esta vacia",
          "sInfo": "Mostrando registros del _START_ al _END_ de un total de _TOTAL_ registros",
          "sInfoEmpty": "Mostrando registros del 0 al 0 de un total de 0 registros",
          "sInfoFiltered": "(filtrado de un total de _MAX_ registros)",
          "sInfoPostFix": "",
          "sSearch": "Buscar:",
          "sUrl": "",
          "sInfoThousands": ",",
          "sLoadingRecords": "Cargando registros...",
          "sPaginate": {
            "sFirst":"<span class='fa fa-angle-double-left'></span>",
            "sLast":"<span class='fa fa-angle-double-right'></span>",
            "sNext":"<span class='fa fa-angle-right'></span>",
            "sPrevious":"<span class='fa fa-angle-left'></span>"
          },
          "oAria":{
            "sSortAscending":": Activar para ordenar la columna de manera ascendente",
            "sSortDescending":": Activar para ordenar la columna de manera descendente"
          }
        }
      });

    });
  </script>
{% endblock js_page %}